# Generated by Django 3.2.23 on 2023-11-15 10:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import ptproject.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='State your name', max_length=100)),
                ('phonenumber', models.CharField(default='1234567890', max_length=15)),
                ('email', models.EmailField(default='your@mail.com', max_length=70)),
                ('age', models.IntegerField(default='0', validators=[django.core.validators.MinValueValidator(0)])),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=10)),
                ('message', models.TextField(default='', max_length=300)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_contact', models.CharField(max_length=100)),
                ('email', models.EmailField(default='default@example.com', max_length=254, unique=True)),
                ('contact_message', models.TextField(blank=True, max_length=400, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alpha[a-zA-Z] characters are allowed.')])),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='default@example.com', max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True, validators=[ptproject.utils.num_validation])),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alpha[a-zA-Z] characters are allowed.')])),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alpha[a-zA-Z] characters are allowed.')])),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
