# Generated by Django 4.2.7 on 2023-11-16 10:11

from django.db import migrations, models
import ptproject.models


class Migration(migrations.Migration):

    dependencies = [
        ('ptproject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_message',
            field=models.TextField(blank=True, max_length=400, null=True, validators=[ptproject.models.alpha_only]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[ptproject.models.alpha_only]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[ptproject.models.alpha_only]),
        ),
    ]
