# Generated by Django 4.2.7 on 2023-11-17 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ptproject', '0003_rename_userprofile_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookingRequest',
            new_name='Booking',
        ),
    ]
