# Generated by Django 4.2.7 on 2023-11-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptproject', '0005_remove_profile_password_booking_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_message',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
