# Generated by Django 4.2.7 on 2024-02-08 13:10

from django.db import migrations
from django.conf import settings


def assign_default_user_to_bookings(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL)
    Booking = apps.get_model('ptproject', 'Booking')  
    default_user = User.objects.get_or_create(username='default_user')[0]  
    
    for booking in Booking.objects.filter(user__isnull=True):
        booking.user = default_user
        booking.save()
class Migration(migrations.Migration):

    dependencies = [
        ('ptproject', '0007_profile_password_alter_booking_age_and_more'),
    ]

    operations = [
        migrations.RunPython(assign_default_user_to_bookings),
    ]

