# Generated by Django 4.2.7 on 2024-02-08 13:25

from django.db import migrations

def fix_null_users(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Booking = apps.get_model('ptproject', 'Booking') 
    default_user = User.objects.filter(is_superuser=True).first()
    if default_user:
        Booking.objects.filter(user__isnull=True).update(user=default_user)

class Migration(migrations.Migration):

    dependencies = [
        ('ptproject', '0008_auto_20240208_1310'),
    ]

    operations = [
        migrations.RunPython(fix_null_users),
    ]
