# Generated by Django 4.2.7 on 2024-02-12 12:41

from django.db import migrations


def assign_default_user(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Booking = apps.get_model('ptproject', 'Booking')
    default_user = User.objects.get_or_create(username='defaultuser')[0]
    Booking.objects.filter(user__isnull=True).update(user=default_user)


class Migration(migrations.Migration):

    dependencies = [
        ('ptproject', '0009_fix_null_users_in_bookings'),
    ]

    operations = [
        migrations.RunPython(assign_default_user),
    ]
