# Generated by Django 4.2.7 on 2024-02-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptproject', '0011_remove_session_participant_booking_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.CharField(choices=[('AM', 'Before Noon'), ('PM', 'After Noon')], default='AM', max_length=2),
        ),
    ]
